### ISSUE TITLE
Error in example code: Missing Chain type.

### ISSUE THREAD

**Issue by ALGW71** [lewis-chinery/Paragraph#1]
Hi @lewis-chinery,

`(feats, coors, edges), (pdb_code, AAs, AtomNum, chain, IMGT, x, y, z) = ds.__getitem__(0)`

Gives an error when run in the example notebook:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [19], line 1
----> 1 (feats, coors, edges), (pdb_code, AAs, AtomNum, chain, IMGT, x, y, z) = ds.__getitem__(0)
      2 (feats, coors, edges), (pdb_code, AAs, AtomNum, chain, IMGT, x, y, z) = ds.__getitem__(0)

ValueError: too many values to unpack (expected 8)

Should this be?

`(feats, coors, edges), (pdb_code, AAs, AtomNum, chain, chain_type, IMGT, x, y, z) = ds.__getitem__(0)`

Think it works now, but not fully run through rest of the example. :)

BW,
Alex

**Comment by ALGW71** [comment]
Ran rest of example code and works now.

**Comment by lewis-chinery** [comment]
Thank you for flagging this! You were absolutely right with the fix and I have now pushed the change.
