### ISSUE TITLE
Interaction sites between antibodies and antigens

### ISSUE THREAD

**Issue by a30221274** [lewis-chinery/Paragraph#3]
Hello, 

Could you please help provide the code for annotating the interaction sites (within 4.5 Å) between antibodies and antigens?

**Comment by lewis-chinery** [comment]
Hi, unfortunately, I don't have that code in a clean format to share, though I will consider cleaning up the full training code and adding this in the future.

For now, I've included the high-level logic and main functions used below:
- Get the x-y-z coordinates of all atoms in the antibody and antigen that you are interested in
- Use scipy's cdist function to get the distances between all antibody and antigen atoms
- Replace these distances with 1 or 0 based on whether or not this distance is below your desired cutoff e.g. 4.5A
- Sum these values per antibody atom (we only care that an antibody atom binds the antigen, not how many interactions it makes)
- Aggregate (sum) these labels at the antibody residue level (you should now have zero values for non-paratope residues and a positive integer for antibody residues that do contact the antigen)
- Replace positive integers with 1 for binary paratope labels

Apologies for not sharing the code right now but I hope the above may be helpful in the meantime!
